import { ActionPanel, Action, List, Icon, environment } from "@raycast/api";
import { join } from "node:path";
import { useState } from "react";
// Generated by `npm run generate-icons` (not committed — see README). Missing on a fresh clone.
import iconsData from "./icons.json";

type Variant = { label: string; px: number; path: string };
type IconEntry = {
  id: string;
  name: string;
  group: string;
  groupLabel: string;
  category: string;
  theme: string | null;
  keywords: string[];
  png: Variant[];
  svg: Variant[];
};

const ICONS = iconsData as unknown as IconEntry[];

// icons.json stores asset-relative paths; clipboard/finder need absolute paths.
const abs = (rel: string) => join(environment.assetsPath, rel);

const GROUPS = [
  { id: "all", label: "All Icons" },
  { id: "service", label: "Architecture · Service" },
  { id: "resource", label: "Resource" },
  { id: "category", label: "Category" },
  { id: "group", label: "Architecture · Group" },
];

// Prefer a crisp 64px thumbnail for the list; fall back to the largest available.
function thumbnail(e: IconEntry): string {
  return (e.png.find((v) => v.label === "64") ?? e.png[0] ?? e.svg[0]).path;
}

export default function Command() {
  const [group, setGroup] = useState("all");
  const items = group === "all" ? ICONS : ICONS.filter((e) => e.group === group);

  return (
    <List
      searchBarPlaceholder="Search AWS icons by service, resource or category…"
      searchBarAccessory={
        <List.Dropdown tooltip="Filter by group" value={group} onChange={setGroup} storeValue>
          {GROUPS.map((g) => (
            <List.Dropdown.Item key={g.id} title={g.label} value={g.id} />
          ))}
        </List.Dropdown>
      }
    >
      <List.Section
        title={group === "all" ? "AWS Icons" : GROUPS.find((g) => g.id === group)?.label}
        subtitle={`${items.length}`}
      >
        {items.map((entry) => (
          <IconItem key={entry.id} entry={entry} />
        ))}
      </List.Section>
    </List>
  );
}

function IconItem({ entry }: { entry: IconEntry }) {
  const png = entry.png[0]; // largest PNG (retina @5x where available)
  const svg = entry.svg[0]; // largest SVG

  const accessories: List.Item.Accessory[] = [{ tag: entry.groupLabel }];
  if (entry.category && entry.group !== "category") {
    accessories.unshift({ text: entry.category });
  }

  return (
    <List.Item
      icon={{ source: thumbnail(entry) }}
      title={entry.name}
      keywords={entry.keywords}
      accessories={accessories}
      actions={
        <ActionPanel>
          {/* Primary: copy the file — paste into Slack, Figma, Keynote, etc. */}
          <ActionPanel.Section>
            {png && (
              <Action.CopyToClipboard
                title={`Copy PNG (${png.label})`}
                icon={Icon.Clipboard}
                content={{ file: abs(png.path) }}
              />
            )}
            {svg && (
              <Action.CopyToClipboard
                title={`Copy SVG (${svg.label})`}
                icon={Icon.Code}
                content={{ file: abs(svg.path) }}
              />
            )}
            {png && <Action.Paste title="Paste PNG" icon={Icon.Clipboard} content={{ file: abs(png.path) }} />}
          </ActionPanel.Section>

          {/* Pick a specific size / format. */}
          <ActionPanel.Section>
            {entry.png.length > 1 && (
              <ActionPanel.Submenu title="Copy PNG as Size…" icon={Icon.Image}>
                {entry.png.map((v) => (
                  <Action.CopyToClipboard
                    key={v.label}
                    title={`${v.label} (${v.px}px)`}
                    content={{ file: abs(v.path) }}
                  />
                ))}
              </ActionPanel.Submenu>
            )}
            {entry.svg.length > 1 && (
              <ActionPanel.Submenu title="Copy SVG as Size…" icon={Icon.Code}>
                {entry.svg.map((v) => (
                  <Action.CopyToClipboard
                    key={v.label}
                    title={`${v.label} (${v.px}px)`}
                    content={{ file: abs(v.path) }}
                  />
                ))}
              </ActionPanel.Submenu>
            )}
          </ActionPanel.Section>

          <ActionPanel.Section>
            <Action.CopyToClipboard title="Copy Icon Name" icon={Icon.Text} content={entry.name} />
            {png && <Action.ShowInFinder path={abs(png.path)} />}
          </ActionPanel.Section>
        </ActionPanel>
      }
    />
  );
}
